name: Build Video Trimmer for Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.3
      
    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Download FFmpeg
      run: |
        python download_ffmpeg.py
      
    - name: Build application
      run: |
        pyinstaller build_app.spec
      
    - name: Verify build output
      run: |
        dir builds\VideoTrimmer
        dir builds\VideoTrimmer\icons
      
    - name: Create icons directory if missing
      run: |
        if (-not (Test-Path -Path "builds\VideoTrimmer\icons")) {
          New-Item -ItemType Directory -Force -Path "builds\VideoTrimmer\icons"
        }
      
    - name: Copy icons to build directory
      run: |
        Copy-Item -Path "icons\*" -Destination "builds\VideoTrimmer\icons\" -Recurse -Force
      
    - name: Create zip archive
      run: |
        $system = [System.Environment]::OSVersion.Platform
        $arch = [System.Environment]::GetEnvironmentVariable("PROCESSOR_ARCHITECTURE")
        $zipName = "VideoTrimmer_Windows_$arch"
        Compress-Archive -Path "builds\VideoTrimmer\*" -DestinationPath "$zipName.zip"
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: VideoTrimmer-Windows
        path: builds/VideoTrimmer/
        
    - name: Upload zip artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: VideoTrimmer-Windows-Zip
        path: VideoTrimmer_Windows_*.zip